Don't depend directly on Vault in MoneyThingParser.
It turns out that the method reference on MobArena#getEconomy() in ThingManager is a tight enough dependency on Vault's Economy interface that it results in a NoClassDefFoundError if Vault isn't present.

By resorting to a more "naive" approach of resolving the Economy instance from the main plugin class on every parse call in MoneyThingParser, the NoClassDefFoundError is avoided along with the load/enable ordering issue that was fixed with the lazy-fetching in commit 2fcb20b2aee838435ff59f3aa9ee7713b2b2963d.

This reverts 2fcb20b2aee838435ff59f3aa9ee7713b2b2963d and partly 4c34a183c7c64120584874b31a5b710349862fd3.

Fixes #463